services:
  redis:
      image: redis:latest
      ports:
        - 6379:6379 
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_PORT=3306
      - PMA_HOST=mysql